name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      # Checkout du code (branche de la PR)
      - name: Checkout du code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Scan de secrets (Gitleaks)
      - name: Scan de secrets (Gitleaks)
        uses: zricethezav/gitleaks-action@v1
        with:
          args: --path=. --verbose

      # Scan des vulnérabilités (OWASP Dependency-Check)
#      - name: Scan des vulnérabilités (OWASP Dependency-Check)
#        uses: dependency-check/Dependency-Check_Action@main
#        with:
#          project: "pull-request-scan"
#          format: "HTML"
#          out: "reports"
#          path: "."
      - name: Scan vulnérabilités (Dependency Check)
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check.zip -d dependency-check
          ./dependency-check/bin/dependency-check.sh --project "todos" --scan . --format "HTML" --out ./dependency-check-report

      # Compilation et tests
      - name: Compilation et tests
        run: mvn clean verify -Put -Pit

      # Analyse Quality Gate avec SonarCloud
      - name: Analyse Quality Gate avec SonarCloud
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=todos \
            -Dsonar.organization=todos \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


      # Vérification du Quality Gate
      - name: Vérifier le Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@master
        with:
          scanMetadataReportFile: target/sonar/report-task.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
